# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChildWindow(object):
    def setupUi(self, ChildWindow):
        ChildWindow.setObjectName("ChildWindow")
        ChildWindow.resize(353, 300)
        self.centralwidget = QtWidgets.QWidget(ChildWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 331, 251))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(40, 40, 91, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(40, 160, 91, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(40, 100, 91, 31))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(140, 40, 113, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 100, 113, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 160, 113, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(260, 50, 61, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(260, 110, 61, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(260, 170, 61, 20))
        self.label_6.setObjectName("label_6")
        self.p1 = QtWidgets.QPushButton(self.groupBox)
        self.p1.setGeometry(QtCore.QRect(80, 200, 75, 23))
        self.p1.setObjectName("p1")
        self.p2 = QtWidgets.QPushButton(self.groupBox)
        self.p2.setGeometry(QtCore.QRect(190, 200, 75, 23))
        self.p2.setObjectName("p2")
        ChildWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChildWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 353, 22))
        self.menubar.setObjectName("menubar")
        ChildWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChildWindow)
        self.statusbar.setObjectName("statusbar")
        ChildWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChildWindow)
        QtCore.QMetaObject.connectSlotsByName(ChildWindow)

    def retranslateUi(self, ChildWindow):
        _translate = QtCore.QCoreApplication.translate
        ChildWindow.setWindowTitle(_translate("ChildWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("ChildWindow", "扫频参数设置"))
        self.label.setText(_translate("ChildWindow", "起始频率："))
        self.label_2.setText(_translate("ChildWindow", "终止频率："))
        self.label_3.setText(_translate("ChildWindow", "频率间距："))
        self.label_4.setText(_translate("ChildWindow", "Hz"))
        self.label_5.setText(_translate("ChildWindow", "Hz"))
        self.label_6.setText(_translate("ChildWindow", "Hz"))
        self.p1.setText(_translate("ChildWindow", "OK"))
        self.p2.setText(_translate("ChildWindow", "CANLE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChildWindow = QtWidgets.QMainWindow()
    ui = Ui_ChildWindow()
    ui.setupUi(ChildWindow)
    ChildWindow.show()
    sys.exit(app.exec_())
